frameworkVersion: "3"
configValidationMode: error

service: my-service

provider:
  name: aws
  architecture: arm64
  runtime: nodejs20.x
  memorySize: 512
  timeout: 29
  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowCredentials: true
  logRetentionInDays: 60
  environment:
    STAGE: "${sls:stage}"
    NODE_OPTIONS: "--enable-source-maps"

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true
    sourcemap: true
    packager: "pnpm"
